package org.msh.etbm.services.cases.tag;

import org.msh.etbm.db.entities.Tag;
import org.msh.etbm.services.session.usersession.UserRequestService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.util.List;
import java.util.UUID;

/**
 * Service to update cases tags links of auto generated tags
 * Created by Mauricio on 25/07/2016.
 */
@Service
public class AutoGenTagsCasesService {

    @PersistenceContext
    EntityManager entityManager;

    @Autowired
    UserRequestService userRequestService;

    /**
     * Update the cases of an auto generated tag
     *
     * @param tagId
     */
    public boolean updateCases(UUID tagId) {
        Tag tag = entityManager.find(Tag.class, tagId);
        if (!tag.isAutogenerated()) {
            return false;
        }

        // remove previous tags
        String sql = "delete from tags_case where tag_id = :id";
        entityManager.createNativeQuery(sql).setParameter("id", tag.getId()).executeUpdate();

        UUID wsid = userRequestService.getUserSession().getWorkspaceId();

        // is tag active ?
        if (tag.isActive()) {
            // include new tags
            sql = "insert into tags_case (case_id, tag_id) " +
                    "select a.id, :tagId from tbcase a join patient p on p.id=a.patient_id " +
                    "where " + tag.getSqlCondition() + " and p.workspace_id = :id";

            entityManager.createNativeQuery(sql)
                    .setParameter("id", wsid)
                    .setParameter("tagId", tag.getId())
                    .executeUpdate();
        }

        return true;
    }

    /**
     * Update the automatic tags of a case
     *
     * @param tbcaseId
     */
    public void updateTags(UUID tbcaseId) {
        UUID wsid = userRequestService.getUserSession().getWorkspaceId();

        // get tags
        List<Tag> tags = entityManager.createQuery("from Tag t where t.active = true " +
                "and t.sqlCondition is not null and t.workspace.id = :wId")
                .setParameter("wId", wsid)
                .getResultList();

        if (tags.isEmpty()) {
            return;
        }

        // erase all tags of the current case
        entityManager.createNativeQuery("delete from tags_case where case_id = :id " +
                "and tag_id in (select id from tag where sqlCondition is not null)")
                .setParameter("id", tbcaseId)
                .executeUpdate();

        // update tags
        for (Tag tag : tags) {
            entityManager.createNativeQuery("insert into tags_case (case_id, tag_id) " +
                                                "select a.id, :tagId " +
                                                    " from tbcase a join patient p on p.id=a.patient_id " +
                                                    " and p.workspace_id = :wId" +
                                                    " and a.id = :tbcaseId " +
                                                    " and " + tag.getSqlCondition())
                    .setParameter("tagId", tag.getId())
                    .setParameter("wId", wsid)
                    .setParameter("tbcaseId", tbcaseId)
                    .executeUpdate();
        }
    }
}
