package org.msh.etbm.commons.sqlquery;

/**
 * Primary exception generated by the SQL Query library
 *
 * Created by rmemoria on 22/8/16.
 */
public class SQLExecException extends RuntimeException {

    public SQLExecException() {
        super();
    }

    public SQLExecException(String message) {
        super(message);
    }

    public SQLExecException(String message, Throwable cause) {
        super(message, cause);
    }

    public SQLExecException(Throwable cause) {
        super(cause);
    }

    protected SQLExecException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
}
