

import React from 'react';
import { Input } from 'react-bootstrap';
import { WaitIcon, SelectionBox } from '../../components';
import Form from '../../forms/form';
import FormUtils from '../../forms/form-utils';


/**
 * Field control to be used in forms to allow the user to select an administrative unit
 */
export default class AdminUnitControl extends React.Component {

	static typeName() {
		return 'adminUnit';
	}

	/**
	 * Display representation of the administrative unit
	 * @param  {[type]} value [description]
	 * @return {[type]}       [description]
	 */
	static displayText(value) {
		if (!value) {
			return '';
		}

		const vals = [];
		let index = 4;
		while (index >= 0) {
			const p = value['p' + index];
			if (p) {
				vals.push(p.name);
			}
			index--;
		}

		return vals.join(', ');
	}


	constructor(props) {
		super(props);
		this.onChange = this.onChange.bind(this);

		this.state = { };
	}

	serverRequest(nextSchema, nextValue, nextResources) {
		// is request necessary ?
		if (nextValue === this.props.value && (this.props.resources || nextResources)) {
			return null;
		}

		return {
			cmd: 'adminUnit',
			params: { value: nextValue }
		};
	}


	/**
	 * Called when the user changes the item selected
	 * @param  {SyntheticEvent} evt The event generated by React
	 */
	onChange(evt, val) {
		if (this.props.onChange) {
			this.props.onChange({ value: val.id, schema: this.props.schema });
		}
	}


	/**
	 * Rend the selection box with administrative units
	 * @param  {[type]} item [description]
	 * @return {[type]}      [description]
	 */
	compRender(item) {
		const schema = this.props.schema || {};

		const ref = 'cb' + item.level;

		const self = this;

		const label = FormUtils.labelRender(item.label, schema.required);

		const errors = item.level === 1 ? this.props.errors : null;

		const val = item.selected ? item.list.find(doc => doc.id === item.selected) : null;

		return (
			<div key={item.level}>
				<SelectionBox ref={ref}
					help={errors} bsStyle={errors ? 'error' : null}
					value={val}
					optionDisplay="name"
					type="select" label={label} onChange={self.onChange}
					noSelectionLabel="-"
					options={item.list} />
				{item.fetching && <WaitIcon type="field" />}
			</div>
			);
	}


	readOnlyRender(schema) {
		const value = this.props.value;
		const s = Form.types.adminUnit.controlClass().displayText(value);

		return (
			<Input
				label={schema.label}
				type="text"
				disabled
				value={s} />
			);
	}


	render() {
		const schema = this.props.schema || {};
		if (schema.readOnly) {
			return this.readOnlyRender(schema);
		}

		if (!this.props.resources) {
			return null;
		}

		const self = this;
		const comps = this.props.resources
			.filter(item => item.list)
			.map(item => self.compRender(item));

		return (
			<div>
				{comps}
			</div>
			);
	}
}


AdminUnitControl.propTypes = {
	value: React.PropTypes.any,
	onChange: React.PropTypes.func,
	schema: React.PropTypes.object,
	errors: React.PropTypes.any,
	resources: React.PropTypes.array
};
