

import React from 'react';
import { Input } from 'react-bootstrap';
import CRUD from '../../commons/crud';
import WaitIcon from '../../components/wait-icon';
import Form from '../../forms/form';
import FormUtils from '../../forms/form-utils';


const crud = new CRUD('adminunit');


class AdminUnitControl extends React.Component {

	constructor(props) {
		super(props);
		this.onChange = this.onChange.bind(this);

		this.state = { };
	}


	componentWillMount() {
		// field is already initialized ?
		if (this.props.resources) {
			return this.setState({ list: this.props.resources });
		}

		// root was loaded ?
		if (!this.state.list) {
			const self = this;

			// request field initialization from server
			FormUtils.initFields([{ id: 'v', type: 'adminUnit', value: this.props.value }])
				.then(res => self.setState({ list: res.v }));
		}
	}

	/**
	 * Display representation of the administrative unit
	 * @param  {[type]} value [description]
	 * @return {[type]}       [description]
	 */
	static displayText(value) {
		if (!value) {
			return '';
		}

		const vals = [];
		let index = 4;
		while (index >= 0) {
			const p = value['p' + index];
			if (p) {
				vals.push(p.name);
			}
			index--;
		}

		return vals.join(', ');
	}

	static isServerInitRequired(sc) {
		return !sc.readOnly;
	}

	/**
	 * Called when the user changes the item selected
	 * @param  {SyntheticEvent} evt The event generated by React
	 */
	onChange(evt) {
		// get the reference of the select box
		const level = Number(evt.currentTarget.dataset.ref);
		const compRef = 'cb' + level;

		const list = this.state.list;

		// get the ID of the selected administrative unit
		const id = this.refs[compRef].getValue();
		const item = list[level - 1];

		// clear list of the next levels
		for (var i = level + 1; i <= 5; i++) {
			const aux = list[i];
			if (aux) {
				aux.list = null;
				aux.selected = null;
			}
		}

		// check if no item was selected
		if (id === '-') {
			item.selected = null;
			this.raiseChangeEvent(null);
			return;
		}

		// search for selected admin unit
		const admUnit = item.list.find(au => au.id === id);

		item.selected = admUnit.id;

		// check if must load other items
		if (level < 5 && admUnit.unitsCount > 0) {
			// get the information about the next level
			const childItem = list[level];
			const self = this;

			item.fetching = true;
			// get children of the parent id
			crud.query({ parentId: id, profile: 'item' })
			.then(res => {
				childItem.list = res.list;
				delete item.fetching;
				self.forceUpdate();
			});
		}

		this.raiseChangeEvent(item.selected);
	}


	raiseChangeEvent(newvalue) {
		if (this.props.onChange) {
			this.props.onChange({ value: newvalue, schema: this.props.schema });
		}

		// force component to update its state
		this.forceUpdate();
	}

	/**
	 * Rend the selection box with administrative units
	 * @param  {[type]} item [description]
	 * @return {[type]}      [description]
	 */
	compRender(item) {
		const schema = this.props.schema || {};

		const options = item.list ?
			item.list.map(opt => (
				<option key={opt.id} value={opt.id}>
					{opt.name}
				</option>
				)) : [];

		options.unshift(<option key="-" value="-" >{'-'}</option>);

		const ref = 'cb' + item.level;

		const self = this;

		const label = FormUtils.labelRender(item.label, schema.required);

		const errors = item.level === 1 ? this.props.errors : null;

		return (
			<div key={item.level}>
				<Input ref={ref} data-ref={item.level} help={errors} bsStyle={errors ? 'error' : null}
					value={item.selected}
					type="select" label={label} onChange={self.onChange}>
					{options}
				</Input>
				{item.fetching && <WaitIcon type="field" />}
			</div>
			);
	}


	readOnlyRender(schema) {
		return (
			<Input
				label={schema.label}
				type="text"
				disabled
				value={Form.types.adminUnit.displayText(this.props.value)} />
			);
	}


	render() {
		const schema = this.props.schema || {};
		if (schema.readOnly) {
			return this.readOnlyRender(schema);
		}

		if (!this.state.list) {
			return null;
		}

		const self = this;
		const comps = this.state.list
			.filter(item => item.list)
			.map(item => self.compRender(item));

		return (
			<div>
				{comps}
			</div>
			);
	}
}

AdminUnitControl.options = {
	supportedTypes: 'adminUnit'
};


AdminUnitControl.propTypes = {
	value: React.PropTypes.string,
	onChange: React.PropTypes.func,
	schema: React.PropTypes.object,
	errors: React.PropTypes.any,
	resources: React.PropTypes.array
};

export default Form.typeWrapper(AdminUnitControl);

