package org.msh.etbm.services.offline.server.sync;

import org.msh.etbm.commons.date.DateUtils;
import org.msh.etbm.services.offline.server.sync.ServerSyncPhase;

import java.io.File;
import java.util.Date;
import java.util.UUID;

/**
 * Data object that stores the state of a sync
 * Created by Mauricio on 07/01/2017.
 */
public class SyncTrack {
    /**
     * The moment that sync has started
     */
    Date iniDateTime;

    /**
     * The sync token of the tracking
     */
    String syncToken;

    /**
     * The sync file sent from client
     */
    File clientSyncFile;

    /**
     * The sync file generated by server
     */
    File serverSyncFile;

    /**
     * The unit that is syncing
     */
    UUID unitId;

    /**
     * The workspace id of the sync unit
     */
    UUID workspaceId;

    /**
     * The user that is syncing
     */
    UUID userId;

    /**
     * The phase of the track
     */
    ServerSyncPhase phase;

    public SyncTrack(String syncToken, File clientSyncFile, UUID workspaceId, UUID userId) {
        this.iniDateTime = DateUtils.getDate();
        this.syncToken = syncToken;
        this.clientSyncFile = clientSyncFile;
        this.workspaceId = workspaceId;
        this.userId = userId;
    }

    public Date getIniDateTime() {
        return iniDateTime;
    }

    public String getSyncToken() {
        return syncToken;
    }

    public void setSyncToken(String syncToken) {
        this.syncToken = syncToken;
    }

    public File getClientSyncFile() {
        return clientSyncFile;
    }

    public void setClientSyncFile(File clientSyncFile) {
        this.clientSyncFile = clientSyncFile;
    }

    public File getServerSyncFile() {
        return serverSyncFile;
    }

    public void setServerSyncFile(File serverSyncFile) {
        this.serverSyncFile = serverSyncFile;
    }

    public UUID getUnitId() {
        return unitId;
    }

    public void setUnitId(UUID unitId) {
        this.unitId = unitId;
    }

    public ServerSyncPhase getPhase() {
        return phase;
    }

    public void setPhase(ServerSyncPhase phase) {
        this.phase = phase;
    }

    public UUID getWorkspaceId() {
        return workspaceId;
    }

    public void setWorkspaceId(UUID workspaceId) {
        this.workspaceId = workspaceId;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }
}
