package org.msh.etbm.commons.forms;

/**
 * Response generated by the service about a field initialization
 *
 * Created by rmemoria on 17/1/16.
 */
public class FieldInitResponse {

    /**
     * The field id, informed on request
     */
    private String id;

    /**
     * The content to be sent to the client to initialize the field form
     */
    private Object result;

    public FieldInitResponse() {
        super();
    }

    public FieldInitResponse(String id, Object result) {
        this.id = id;
        this.result = result;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Object getResult() {
        return result;
    }

    public void setResult(Object result) {
        this.result = result;
    }
}
