package org.msh.etbm.commons.commands.impl;

/**
 * Exception generated by command execution
 * Created by rmemoria on 17/10/15.
 */
public class CommandException extends RuntimeException {
    public CommandException() {
    }

    public CommandException(String message) {
        super(message);
    }

    public CommandException(String message, Throwable cause) {
        super(message, cause);
    }

    public CommandException(Throwable cause) {
        super(cause);
    }

    public CommandException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
}
