
import React from 'react';
import CRUD from '../../../commons/crud';
import CrudView from '../crud-view';
import Profile from '../../../components/profile';


const crud = new CRUD('tag');

// definition of the form fields to edit substances
const editorDef = {
	defaultProperties: {
		autoGenerated: doc => typeof doc.sqlCondition === 'string'
	},
	layout: [
		{
			property: 'name',
			required: true,
			type: 'string',
			max: 200,
			label: __('form.name'),
			size: { sm: 8 }
		},
		{
			property: 'active',
			type: 'yesNo',
			label: __('EntityState.ACTIVE'),
			size: { newLine: true, sm: 6 },
			defaultValue: true
		},
		{
			property: 'autoGenerated',
			type: 'yesNo',
			label: __('Tag.autogenerated'),
			size: { sm: 6 },
			defaultValue: false
		},
		{
			el: 'group',
			visible: value => value.autoGenerated,
			layout: [
				{
					property: 'consistencyCheck',
					type: 'yesNo',
					label: __('Tag.consistencyCheck'),
					size: { newLine: true, sm: 6 },
					defaultValue: false
				},
				{
					property: 'sqlCondition',
					type: 'text',
					label: __('Tag.sqlCondition'),
					size: { sm: 12 }
				}
			]
		}
	],
	title: doc => doc && doc.id ? __('admin.substances.edt') : __('admin.substances.new')
};

/**
 * The page controller of the public module
 */
export default class Tags extends React.Component {

	constructor(props) {
		super(props);
		this.cellRender = this.cellRender.bind(this);
	}

	cellRender(item) {
		let type;

		if (item.sqlCondition) {
			type = item.consistencyCheck ? 'danger' : 'warn';
		}
		else {
			type = 'userdef';
		}

		type = 'prof-tag-' + type;

		return <Profile imgClass={type} fa="tag" title={item.name} size="small" />;
	}

	collapseCellRender(item) {
		return (
			<div>
				<hr/>
				<dl className="text-small dl-horizontal text-muted">
					<dt>{__('Tag.consistencyCheck') + ':'}</dt>
					<dd>{item.consistencyCheck}</dd>
					<dt>{__('Tag.sqlCondition') + ':'}</dt>
					<dd>{item.sqlCondition}</dd>
				</dl>
				<hr/>
			</div>
			);
	}

	render() {
		// get information about the route of this page
		const data = this.props.route.data;

		return (
			<CrudView crud={crud}
				title={data.title}
				onCellRender={this.cellRender}
				onDetailRender={this.collapseCellRender}
				editorDef={editorDef}
				perm={data.perm} />
			);
	}
}

Tags.propTypes = {
	route: React.PropTypes.object
};
